### ISSUE TITLE
Issue in last sublime stable (3124)

### ISSUE THREAD

**Issue by marc0n3** [martomo/SublimeTextXdebug#163]
Hi everyone, am I the only one that has problems with Xdebug plugin on new releases?
On 3114 it works, developer versions and the new 3124 prompts:

Exception in thread Thread-617:
Traceback (most recent call last):
File "./python3.3/threading.py", line 901, in bootstrapinner
File "xdebug.session in /home/marco/.config/sublime-text-3/Installed Packages/Xdebug Client.sublime-package", line 151, in run
File "xdebug.session in /home/marco/.config/sublime-text-3/Installed Packages/Xdebug Client.sublime-package", line 364, in init
File "xdebug.session in /home/marco/.config/sublime-text-3/Installed Packages/Xdebug Client.sublime-package", line 417, in set_breakpoint
File "xdebug.util in /home/marco/.config/sublime-text-3/Installed Packages/Xdebug Client.sublime-package", line 42, in get_real_path
File "xdebug.helper.helper in /home/marco/.config/sublime-text-3/Installed Packages/Xdebug Client.sublime-package", line 17, in url_decode
AttributeError: 'module' object has no attribute 'parse'

I'm on debian linux.

Thanks in advance.

**Comment by jacarvajal** [comment]
I couldn't see this errors (I don't know how to show this prompt), but after update Sublime Text to 3124, xDebug client started to fail the same way.

So, I subscribe to this.

I use Ubuntu 14.04.

Thank you!

**Comment by marc0n3** [comment]
I've foud a way to make it works, it seems.... testing it right now https://github.com/marc0n3/SublimeTextXdebug/commit/543ff43f9f007de7d679ad017565e5dff49e047e

**Comment by yoX64** [comment]
This fix works.

Great work, @marc0n3 :+1:

**Comment by laurent22** [comment]
For information, this bug also affects other plugins (like URLDecode for instance). The fix is to uninstall and reinstall Package Control, as described there:

https://forum.sublimetext.com/t/module-error-when-running-a-plugin/23611

**Comment by marc0n3** [comment]
I've closed the project because the issue was not the plugin. This was
solved by removing config dir and reinstalling sublime and package control.
It seems to be something that doesn't get updated by package control.

Good luck!
Marco


Il 29 dic 2016 04:24, "chenyingqiao" <notifications@github.com> ha scritto:

**Comment by tim0991** [comment]
@marc0n3 @laurent22 @yoX64 
i am in osx, and sublime version is 3126, i appeared the same problem

i remove sublime config , reinstall sublime ,reinstall package control, reinstall xdebug

but it still do not work, what should i do

**Comment by bwbroersma** [comment]
@tim0991 
what you should do: patch it, but you no longer have to, I just did ;)

**Comment by martomo** [comment]
I've tried both Sublime build 3126 and 3142 on Windows/macOS, but I was unable to reproduce the error. It seems to me, as pointed out by @laurent22, this is/was an issue with the installation of Package Control.
